// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfyzH_sgIER9slFqg9-AU-doWDDaDKLeA',
    appId: '1:140124678871:web:bdb082b4de844ec74e5e92',
    messagingSenderId: '140124678871',
    projectId: 'flutter-chat-app-tutoria-47554',
    authDomain: 'flutter-chat-app-tutoria-47554.firebaseapp.com',
    storageBucket: 'flutter-chat-app-tutoria-47554.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDD4JmbklTjGm5VVnFpLILkBvMImXez0Ks',
    appId: '1:140124678871:android:4e1061d12f070dff4e5e92',
    messagingSenderId: '140124678871',
    projectId: 'flutter-chat-app-tutoria-47554',
    storageBucket: 'flutter-chat-app-tutoria-47554.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiwzcZ8DUG2-GwvwwOENU3EhXHv3LYlDM',
    appId: '1:140124678871:ios:8e757c5918fba4cc4e5e92',
    messagingSenderId: '140124678871',
    projectId: 'flutter-chat-app-tutoria-47554',
    storageBucket: 'flutter-chat-app-tutoria-47554.appspot.com',
    iosBundleId: 'com.example.flutterChatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBiwzcZ8DUG2-GwvwwOENU3EhXHv3LYlDM',
    appId: '1:140124678871:ios:8e757c5918fba4cc4e5e92',
    messagingSenderId: '140124678871',
    projectId: 'flutter-chat-app-tutoria-47554',
    storageBucket: 'flutter-chat-app-tutoria-47554.appspot.com',
    iosBundleId: 'com.example.flutterChatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDfyzH_sgIER9slFqg9-AU-doWDDaDKLeA',
    appId: '1:140124678871:web:3623e1de9cd0cfd94e5e92',
    messagingSenderId: '140124678871',
    projectId: 'flutter-chat-app-tutoria-47554',
    authDomain: 'flutter-chat-app-tutoria-47554.firebaseapp.com',
    storageBucket: 'flutter-chat-app-tutoria-47554.appspot.com',
  );
}
